pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
        stage('who am i') {
            steps {
                sh 'whoami'
            }
        }
        stage('mvn -v') {
            steps {
                sh 'mvn -v'
            }
        }
        stage('docker -v') {
            steps {
                sh 'docker -v'
            }
        }
        stage('docker start') {
            steps {
                sh 'docker start eb287e2bf177'
            }
        }
    }
}
